services:
  - type: web
    name: tenerifepictures
    env: python
    plan: starter
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
